### ISSUE TITLE
Whereami don't work

### ISSUE THREAD

**Issue by DmitryAvramec** [mesmerze/Constantine#2]
When i call MAGIC WORD somewhere i can't see my code after whereami

**Comment by mesmerze** [comment]
Can you please provide test app, which reproduces the problem?

**Comment by DmitryAvramec** [comment]
When i try to use `whereami` from console after i start debug, i want to see from where MAGIC WORD call this. 
This is what we have now: 
![whereami](https://user-images.githubusercontent.com/23083062/36632302-3b520ee8-1996-11e8-9c8c-0fa3b8c86c19.png)
And we need to see not action name, we must see code where it's called

**Comment by DmitryAvramec** [comment]
Fixed by #4
